name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_URI: ${{secrets.MONGODB_URI}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Run Lint
        run: npm run lint-check

      - name: Run tests
        run: npm run test
